CREATE OR REPLACE FUNCTION array_sum(arr anyarray)
	RETURNS ANYELEMENT
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION array_avg(arr anyarray)
	RETURNS float8
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION array_median(arr anyarray)
	RETURNS float8
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;
 
CREATE OR REPLACE FUNCTION array_min(arr anyarray)
	RETURNS ANYELEMENT
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION array_max(arr anyarray)
	RETURNS ANYELEMENT
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION array_sort(arr anyarray, reverse boolean DEFAULT false)
	RETURNS ANYARRAY
	AS 'MODULE_PATHNAME'
	LANGUAGE 'c'
	IMMUTABLE STRICT;
