# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-22.04

    # Github Runner for Ubuntu 22.04
    # has PgSQL 14 installed by default
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#postgresql
    # We remove that, and then install the
    # version we are testing.
    env:
      OS_PGVER: 14
      OS_NAME: jammy-pgdg


    name: "CI"
    strategy:
      matrix:
        ci:
        - { PGVER: 12 }
        - { PGVER: 13 }
        - { PGVER: 14 }
        - { PGVER: 15 }

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Uninstall PostgreSQL'
      run: |
        sudo apt-get -y -f --ignore-missing --purge remove postgresql postgresql-common postgresql-14
        sudo apt-get -y autoremove
        sudo rm -rf /var/lib/postgresql

    - name: 'Install PostgreSQL'
      run: |
        export PGVER=${{ matrix.ci.PGVER }}
        export PGDATA=/var/lib/postgresql/$PGVER/main
        export PGETC=/etc/postgresql/$PGVER/main
        export PGBIN=/usr/lib/postgresql/$PGVER/bin
        env
        curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $OS_NAME main $PGVER"
        sudo apt-get -y install libcurl4-gnutls-dev postgresql-server-dev-$PGVER postgresql-client-$PGVER postgresql-$PGVER
        sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA stop"
        sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
        sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA start -o '-c config_file=$PGETC/postgresql.conf'"

    - name: 'Build & Test'
      run: |
        export PATH=/usr/lib/postgresql/$PGVER/bin/:$PATH
        make DEBUG=1 all
        sudo make install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)
