# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest

    name: "CI"
    strategy:
      matrix:
        ci:
        - { PGVER: 12 }
        - { PGVER: 13 }
        - { PGVER: 14 }
        - { PGVER: 15 }

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Install PostgreSQL'
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg-snapshot main ${{ matrix.ci.PGVER }}" > /etc/apt/sources.list.d/pgdg.list'
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
        sudo apt-get update
        sudo apt-get -y install postgresql-${{ matrix.ci.PGVER }} postgresql-server-dev-${{ matrix.ci.PGVER }}

    - name: 'Start PostgreSQL'
      run: |
        export PGVER=${{ matrix.ci.PGVER }}
        export PGDATA=/var/lib/postgresql/$PGVER/main
        export PGETC=/etc/postgresql/$PGVER/main
        export PGBIN=/usr/lib/postgresql/$PGVER/bin
        sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
        sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA start -o '-c config_file=$PGETC/postgresql.conf -p 5432'"

    - name: 'Build & Test'
      run: |
        export PGVER=${{ matrix.ci.PGVER }}
        export PGBIN=/usr/lib/postgresql/$PGVER/bin
        export PATH=$PGBIN:$PATH
        export PG_CONFIG=$PGBIN/pg_config
        export PG_CFLAGS=-Werror
        make
        sudo -E make PG_CONFIG=$PG_CONFIG install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)

